### ISSUE TITLE
Add support for "mandatory" state updates

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/controllers#112]
Currently the method `BaseController.putState(state: object, forceUpdate: bool)` is synchronous, and merely emits a state update, leaving persistence as an external concern, not coupled with controller logic.

I am working on a feature that will require guaranteed persistence to be coupled with some types of state updates, so I would like a way to update state that returns a promise and resolves once state has been persisted, so that it will be restored in the case of a system interruption.

## Example use case

Let's say we add a login permission that enforces a rule like "This site may update my profile 5 times."

In order to enforce this rule, we need to ensure that portions of the state, namely:

- update counter
- outbound profile update messages

Are always persisted atomically, so that we never broadcast a profile update without also accounting for the site's limit.

This is about enforcing smart-contract-like guarantees within our own controllers, and if we want to decouple our security from constant user nagging, I believe this is a critical feature to pursue.

This will probably require `gaba` to become somewhat aware of its persistence strategy.

**Comment by Gudahtt** [comment]
>I would like a way to update state that returns a promise and resolves once state has been persisted, so that it will be restored in the case of a system interruption.

What about state updates for things that aren't persisted at all? Or state updates that trigger a network request that you also want to ensure has completed successfully before continuing?

This sort of thing may be better handled at a different layer than the BaseController update method. Controllers are responsible for ensuring their state remains valid, so this seems like ti should be their responsibility. For example, a "profile controller" could expose an "update profile" function that respected a permission based upon a counter.

**Comment by Gudahtt** [comment]
Closing for now, as I think this is better handled at a different layer than in the base controller API. We can revisit when we have a feature that needs this.
