### ISSUE TITLE
Pass EthQuery instance into controllers

### ISSUE THREAD

**Issue by bitpshr** [MetaMask/controllers#12]
Many controllers accept a `provider` configuration property and internally create an EthQuery instance. We should make the NetworkControllers internal EthQuery instance public, and pass that into each controller instead of the provider.

This may be too restrictive, but it should be investigated.

**Comment by Gudahtt** [comment]
We will be extracting network interactions to separate modules rather than leaving them embedded within controllers, so I will close this as obsolete.
