### ISSUE TITLE
get list of tokens from Web3

### ISSUE THREAD

**Issue by stanta** [MetaMask/controllers#240]
Hi, @estebanmino!
Will be a lot of thanks for the advice, how can be received a list of tokens by Web3 from AssetsState?

https://github.com/MetaMask/controllers/blob/82c29fac98e3073d15f93d59d6da8f2f616115a7/src/AssetsController.ts#L64

**Comment by Gudahtt** [comment]
Hi @stanta! Unfortunately I'm having trouble understanding your question. Could you explain what you're trying to do?

**Comment by stanta** [comment]
@Gudahtt , how can I get the list of assets (tokens), added to Metamask Asset tab?

**Comment by Gudahtt** [comment]
Are you asking how to add a token to that list, as a user? Or how to add a token programmatically from a dapp? Or how to retrieve the list of tokens programmatically from a dapp?

**Comment by stanta** [comment]
programmatically from a dapp

**Comment by Gudahtt** [comment]
There is no way to retrieve the list of the users tokens unfortunately. We don't share any information like that about the user without asking for explicit consent, and to my knowledge nobody has proposed a way of doing that yet.


You can suggest that a user add a token to their list though. The docs for that are here: https://docs.metamask.io/guide/registering-your-token.html
