### ISSUE TITLE
Remove or update NetworkStatusController

### ISSUE THREAD

**Issue by danjm** [MetaMask/controllers#296]
The network controller relies on https://api.infura.io/v1/status/metamask, which is depracated.

This endpoint's only use case is showing a message about network status in mobile. That usage is currently broken, and shows the network status as good/operational regardless of the actually network status.

We either need to remove this controller or update it. The former can be a short term solution to unit tests failing on develop. The latter is what we need to do to eventually support correct display of network status in mobile. The latter will require use of an endpoint like https://hfq2h9152m63.statuspage.io/api/v2/components.json, or a proxy for status should we so choose.

**Comment by Gudahtt** [comment]
This was removed in #298
