### ISSUE TITLE
TransactionController should Compose with PreferencesController

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/controllers#34]
So the state can only expose the list of transactions for the selected address and current network

**Comment by bitpshr** [comment]
Part of me feels like the TransactionController's state shouldn't be limited to the transactions corresponding to the currently-selected address and the current network. This seems like something that downstream applications should handle when rendering a transaction list if they desire, and that the controller should always maintain all transactions a user has sent.

FWIW, we already only check the current network ID from the NetworkController when updating transaction statuses.

**Comment by Gudahtt** [comment]
We are migrating away from the old controller composition system, so this is now obsolete.
