### ISSUE TITLE
Prevent exceptions from interrupting controller messenger event processing

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/controllers#566]
Currently, if a controller messenger event handler or selector throws, processing will be interrupted, and none of the subsequent handlers will be called. We should ensure that all event handlers are always called, ala [`safe-event-emitter`](https://github.com/MetaMask/safe-event-emitter/blob/faf5620ac17ac6d32d8dd00ba0c3ffd9247ee6cf/index.ts/#L8-L17).

**Comment by Gudahtt** [comment]
@rekmarks Considering the latest comments on #567, do you think we can close this? As far as I can see, the way this works right now is pretty reasonable. We can instead ensure that we fix any instances of crashing handlers that we find.

**Comment by Gudahtt** [comment]
Closing for reasons mentioned in last comment. Can re-open if we discover otherwise.
