### ISSUE TITLE
Use eth_feeHistory to calculate gas estimates when gas api is down

### ISSUE THREAD

**Issue by danjm** [MetaMask/controllers#600]
This is an improvement that can be made in the gas controller. Currently, if the gas api is down, we fall back to `eth_gasPrice` to provide the user with an estimate. This can be inaccurate, and also means that we cannot provide a slow/medium/fast recommendation to the user.

Now the `eth_feeHistory` is available to us, we should fall back to calling that and using its results to calculate the gas fee estimates. We can use the same logic that is used on the server.

That logic currently relies on some constants. We could consider adding a server endpoint for those constants, and retrieving them once a day (or something like that) so that our fallback logic can be updated without a new deployment (if necessary)

**Comment by mcmire** [comment]
Waiting for #661 to be merged.

**Comment by mcmire** [comment]
This is done, so closing.
