### ISSUE TITLE
getDetails method in ERC721Standard and ERC1155Standard classes should return image/description instead of TokenURI

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/controllers#689]
The `getDetails` methods for `ERC721Standard` and `ERC1155Standard` currently fetch and return a tokenURI. Ideally they would  fetch the tokenURI and then use it to fetch other more useful details like `image` `name` and `description` (possibly more) as we do in the `getCollectibleInformationFromTokenURI` method of the `CollectiblesController`.

**Comment by adonesky1** [comment]
cc @gantunesr @wachunei, tagging you both for thoughts/visibility.

**Comment by wachunei** [comment]
sounds right, `getTokenURI` should return the UR and `getDetails` should resolve it.
I'm thinking about the case the `tokenURI` is a data URI, or a decentralized fs protocol like IPFS, for now we'll support `https` protocol only, right?

**Comment by wachunei** [comment]
re ipfs: cool 👍 
re data uri: I mean something like `data:application/json;base64,ew0KICAgICJ...`
