### ISSUE TITLE
KeyringController:submitPassword should fail for wrong password

### ISSUE THREAD

**Issue by jpuri** [MetaMask/controllers#798]
While working on test coverage I found an issue that `KeyringController:submitPassword` works well even if wrong password is passed. Function call should fail for wrong password.

**Comment by Gudahtt** [comment]
I believe the unit tests are showing this only because the mock encryptor used will never verify the password. See: https://github.com/MetaMask/controllers/blob/main/tests/mocks/mockEncryptor.ts

**Comment by jpuri** [comment]
Agree that seems to be likely cause
