### ISSUE TITLE
Prototype monorepo architecture

### ISSUE THREAD

**Issue by mcmire** [MetaMask/controllers#823]
The way we maintain `controllers` currently will change when we convert it to a monorepo, and we need to work out those changes. I'm going to research this by making another repo, privately, where I can experiment with some ideas and work out some processes. I'll post my learnings as I go along.

**Comment by mcmire** [comment]
I've made a PR where I talk about some of the things I found and offer some possible solutions: https://github.com/MetaMask/controllers/pull/831. I think I can mark this as complete now.

**Comment by Gudahtt** [comment]
Closed by https://www.notion.so/Core-Monorepo-Release-Automation-a65b28ab89a14c9d82dcf9fabc3eb1e1
