### ISSUE TITLE
Sort out monorepo release process

### ISSUE THREAD

**Issue by mcmire** [MetaMask/controllers#835]
The most challenging part about creating a monorepo structure is to decide how the release process should work. Once we have a plan, then we know how to change `action-create-release-pr`, `action-publish-release`, and `action-npm-publish`.

**Comment by mcmire** [comment]
I've posted some ideas in this Notion doc: https://www.notion.so/Monorepo-Release-Automation-a65b28ab89a14c9d82dcf9fabc3eb1e1

**Comment by Gudahtt** [comment]
Closed by https://www.notion.so/Core-Monorepo-Release-Automation-a65b28ab89a14c9d82dcf9fabc3eb1e1
